"""
Visualization script for F# Quantum Game of Life output
Reads CSV files generated by the F# implementation and creates visualizations
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

def load_quantum_state(filename):
    """Load quantum state from CSV file."""
    return np.loadtxt(filename, delimiter=',')

def visualize_fsharp_output():
    """Create visualizations from F# output files."""
    
    # Load the different time steps
    steps = [0, 10, 20, 30, 40, 50]
    output_dir = Path('/mnt/user-data/outputs')
    
    # Create figure for probability evolution
    fig, axes = plt.subplots(2, 3, figsize=(15, 10))
    
    for idx, step in enumerate(steps):
        filename = output_dir / f'quantum_state_step_{step:03d}.csv'
        
        if filename.exists():
            state = load_quantum_state(filename)
            
            ax = axes[idx // 3, idx % 3]
            im = ax.imshow(state, cmap='viridis', vmin=0, vmax=1)
            ax.set_title(f'Step {step} - Probability |ψ|²', fontsize=12)
            ax.axis('off')
            plt.colorbar(im, ax=ax, fraction=0.046, pad=0.04)
        else:
            print(f"Warning: {filename} not found")
    
    plt.suptitle('Quantum Game of Life Evolution (F# Implementation)', fontsize=16, y=0.995)
    plt.tight_layout()
    
    output_file = output_dir / 'fsharp_quantum_evolution.png'
    plt.savefig(output_file, dpi=150, bbox_inches='tight')
    print(f"Saved visualization to {output_file}")
    
    # Create comparison plot (initial vs final)
    fig2, (ax1, ax2, ax3) = plt.subplots(1, 3, figsize=(15, 5))
    
    initial = load_quantum_state(output_dir / 'quantum_state_step_000.csv')
    final = load_quantum_state(output_dir / 'quantum_state_step_050.csv')
    difference = final - initial
    
    im1 = ax1.imshow(initial, cmap='viridis', vmin=0, vmax=1)
    ax1.set_title('Initial State (Step 0)')
    ax1.axis('off')
    plt.colorbar(im1, ax=ax1)
    
    im2 = ax2.imshow(final, cmap='viridis', vmin=0, vmax=1)
    ax2.set_title('Final State (Step 50)')
    ax2.axis('off')
    plt.colorbar(im2, ax=ax2)
    
    im3 = ax3.imshow(difference, cmap='RdBu_r', vmin=-1, vmax=1)
    ax3.set_title('Difference (Final - Initial)')
    ax3.axis('off')
    plt.colorbar(im3, ax=ax3)
    
    plt.suptitle('Quantum State Evolution Comparison', fontsize=16)
    plt.tight_layout()
    
    comparison_file = output_dir / 'fsharp_quantum_comparison.png'
    plt.savefig(comparison_file, dpi=150, bbox_inches='tight')
    print(f"Saved comparison to {comparison_file}")
    
    plt.show()

if __name__ == "__main__":
    visualize_fsharp_output()
